run:
  skip-files:
  - ".*_test.go"
  - ".*.gen.go"
  - pkg/utils/http/reverse_proxy.go
  - pkg/proxy/apiserver/options.go
  - pkg/proxy/apiserver/common/options.go
  skip-dirs:
  - vendor/

linters:
  disable:
  - errcheck
  - unused
