apiVersion: v1
kind: Service
metadata:
  labels:
    kridge.kusionstack.io/ignore-webhook: "true"
  name: kridge-webhook-service
  namespace: kridge
spec:
  clusterIP: None
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: kridge
  type: ClusterIP