/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/KusionStack/ctrlmesh/pkg/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShardingConfigs implements ShardingConfigInterface
type FakeShardingConfigs struct {
	Fake *FakeCtrlmeshV1alpha1
	ns   string
}

var shardingconfigsResource = schema.GroupVersionResource{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Resource: "shardingconfigs"}

var shardingconfigsKind = schema.GroupVersionKind{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Kind: "ShardingConfig"}

// Get takes name of the shardingConfig, and returns the corresponding shardingConfig object, and an error if there is any.
func (c *FakeShardingConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ShardingConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(shardingconfigsResource, c.ns, name), &v1alpha1.ShardingConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShardingConfig), err
}

// List takes label and field selectors, and returns the list of ShardingConfigs that match those selectors.
func (c *FakeShardingConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ShardingConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(shardingconfigsResource, shardingconfigsKind, c.ns, opts), &v1alpha1.ShardingConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ShardingConfigList{ListMeta: obj.(*v1alpha1.ShardingConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.ShardingConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shardingConfigs.
func (c *FakeShardingConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(shardingconfigsResource, c.ns, opts))

}

// Create takes the representation of a shardingConfig and creates it.  Returns the server's representation of the shardingConfig, and an error, if there is any.
func (c *FakeShardingConfigs) Create(ctx context.Context, shardingConfig *v1alpha1.ShardingConfig, opts v1.CreateOptions) (result *v1alpha1.ShardingConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(shardingconfigsResource, c.ns, shardingConfig), &v1alpha1.ShardingConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShardingConfig), err
}

// Update takes the representation of a shardingConfig and updates it. Returns the server's representation of the shardingConfig, and an error, if there is any.
func (c *FakeShardingConfigs) Update(ctx context.Context, shardingConfig *v1alpha1.ShardingConfig, opts v1.UpdateOptions) (result *v1alpha1.ShardingConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(shardingconfigsResource, c.ns, shardingConfig), &v1alpha1.ShardingConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShardingConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeShardingConfigs) UpdateStatus(ctx context.Context, shardingConfig *v1alpha1.ShardingConfig, opts v1.UpdateOptions) (*v1alpha1.ShardingConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(shardingconfigsResource, "status", c.ns, shardingConfig), &v1alpha1.ShardingConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShardingConfig), err
}

// Delete takes name of the shardingConfig and deletes it. Returns an error if one occurs.
func (c *FakeShardingConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(shardingconfigsResource, c.ns, name, opts), &v1alpha1.ShardingConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShardingConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(shardingconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ShardingConfigList{})
	return err
}

// Patch applies the patch and returns the patched shardingConfig.
func (c *FakeShardingConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ShardingConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(shardingconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ShardingConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShardingConfig), err
}
