/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCircuitBreakers implements CircuitBreakerInterface
type FakeCircuitBreakers struct {
	Fake *FakeCtrlmeshV1alpha1
	ns   string
}

var circuitbreakersResource = schema.GroupVersionResource{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Resource: "circuitbreakers"}

var circuitbreakersKind = schema.GroupVersionKind{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Kind: "CircuitBreaker"}

// Get takes name of the circuitBreaker, and returns the corresponding circuitBreaker object, and an error if there is any.
func (c *FakeCircuitBreakers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(circuitbreakersResource, c.ns, name), &v1alpha1.CircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CircuitBreaker), err
}

// List takes label and field selectors, and returns the list of CircuitBreakers that match those selectors.
func (c *FakeCircuitBreakers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CircuitBreakerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(circuitbreakersResource, circuitbreakersKind, c.ns, opts), &v1alpha1.CircuitBreakerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CircuitBreakerList{ListMeta: obj.(*v1alpha1.CircuitBreakerList).ListMeta}
	for _, item := range obj.(*v1alpha1.CircuitBreakerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested circuitBreakers.
func (c *FakeCircuitBreakers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(circuitbreakersResource, c.ns, opts))

}

// Create takes the representation of a circuitBreaker and creates it.  Returns the server's representation of the circuitBreaker, and an error, if there is any.
func (c *FakeCircuitBreakers) Create(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.CreateOptions) (result *v1alpha1.CircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(circuitbreakersResource, c.ns, circuitBreaker), &v1alpha1.CircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CircuitBreaker), err
}

// Update takes the representation of a circuitBreaker and updates it. Returns the server's representation of the circuitBreaker, and an error, if there is any.
func (c *FakeCircuitBreakers) Update(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (result *v1alpha1.CircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(circuitbreakersResource, c.ns, circuitBreaker), &v1alpha1.CircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CircuitBreaker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCircuitBreakers) UpdateStatus(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (*v1alpha1.CircuitBreaker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(circuitbreakersResource, "status", c.ns, circuitBreaker), &v1alpha1.CircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CircuitBreaker), err
}

// Delete takes name of the circuitBreaker and deletes it. Returns an error if one occurs.
func (c *FakeCircuitBreakers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(circuitbreakersResource, c.ns, name, opts), &v1alpha1.CircuitBreaker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCircuitBreakers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(circuitbreakersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CircuitBreakerList{})
	return err
}

// Patch applies the patch and returns the patched circuitBreaker.
func (c *FakeCircuitBreakers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CircuitBreaker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(circuitbreakersResource, c.ns, name, pt, data, subresources...), &v1alpha1.CircuitBreaker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CircuitBreaker), err
}
