/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagerStates implements ManagerStateInterface
type FakeManagerStates struct {
	Fake *FakeCtrlmeshV1alpha1
}

var managerstatesResource = schema.GroupVersionResource{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Resource: "managerstates"}

var managerstatesKind = schema.GroupVersionKind{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Kind: "ManagerState"}

// Get takes name of the managerState, and returns the corresponding managerState object, and an error if there is any.
func (c *FakeManagerStates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagerState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(managerstatesResource, name), &v1alpha1.ManagerState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerState), err
}

// List takes label and field selectors, and returns the list of ManagerStates that match those selectors.
func (c *FakeManagerStates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagerStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(managerstatesResource, managerstatesKind, opts), &v1alpha1.ManagerStateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagerStateList{ListMeta: obj.(*v1alpha1.ManagerStateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagerStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managerStates.
func (c *FakeManagerStates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(managerstatesResource, opts))
}

// Create takes the representation of a managerState and creates it.  Returns the server's representation of the managerState, and an error, if there is any.
func (c *FakeManagerStates) Create(ctx context.Context, managerState *v1alpha1.ManagerState, opts v1.CreateOptions) (result *v1alpha1.ManagerState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(managerstatesResource, managerState), &v1alpha1.ManagerState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerState), err
}

// Update takes the representation of a managerState and updates it. Returns the server's representation of the managerState, and an error, if there is any.
func (c *FakeManagerStates) Update(ctx context.Context, managerState *v1alpha1.ManagerState, opts v1.UpdateOptions) (result *v1alpha1.ManagerState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(managerstatesResource, managerState), &v1alpha1.ManagerState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerState), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagerStates) UpdateStatus(ctx context.Context, managerState *v1alpha1.ManagerState, opts v1.UpdateOptions) (*v1alpha1.ManagerState, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(managerstatesResource, "status", managerState), &v1alpha1.ManagerState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerState), err
}

// Delete takes name of the managerState and deletes it. Returns an error if one occurs.
func (c *FakeManagerStates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(managerstatesResource, name, opts), &v1alpha1.ManagerState{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagerStates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(managerstatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagerStateList{})
	return err
}

// Patch applies the patch and returns the patched managerState.
func (c *FakeManagerStates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagerState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(managerstatesResource, name, pt, data, subresources...), &v1alpha1.ManagerState{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagerState), err
}
