/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFaultInjections implements FaultInjectionInterface
type FakeFaultInjections struct {
	Fake *FakeCtrlmeshV1alpha1
	ns   string
}

var faultinjectionsResource = schema.GroupVersionResource{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Resource: "faultinjections"}

var faultinjectionsKind = schema.GroupVersionKind{Group: "ctrlmesh.kusionstack.io", Version: "v1alpha1", Kind: "FaultInjection"}

// Get takes name of the faultInjection, and returns the corresponding faultInjection object, and an error if there is any.
func (c *FakeFaultInjections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FaultInjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(faultinjectionsResource, c.ns, name), &v1alpha1.FaultInjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultInjection), err
}

// List takes label and field selectors, and returns the list of FaultInjections that match those selectors.
func (c *FakeFaultInjections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FaultInjectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(faultinjectionsResource, faultinjectionsKind, c.ns, opts), &v1alpha1.FaultInjectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FaultInjectionList{ListMeta: obj.(*v1alpha1.FaultInjectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.FaultInjectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested faultInjections.
func (c *FakeFaultInjections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(faultinjectionsResource, c.ns, opts))

}

// Create takes the representation of a faultInjection and creates it.  Returns the server's representation of the faultInjection, and an error, if there is any.
func (c *FakeFaultInjections) Create(ctx context.Context, faultInjection *v1alpha1.FaultInjection, opts v1.CreateOptions) (result *v1alpha1.FaultInjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(faultinjectionsResource, c.ns, faultInjection), &v1alpha1.FaultInjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultInjection), err
}

// Update takes the representation of a faultInjection and updates it. Returns the server's representation of the faultInjection, and an error, if there is any.
func (c *FakeFaultInjections) Update(ctx context.Context, faultInjection *v1alpha1.FaultInjection, opts v1.UpdateOptions) (result *v1alpha1.FaultInjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(faultinjectionsResource, c.ns, faultInjection), &v1alpha1.FaultInjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultInjection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFaultInjections) UpdateStatus(ctx context.Context, faultInjection *v1alpha1.FaultInjection, opts v1.UpdateOptions) (*v1alpha1.FaultInjection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(faultinjectionsResource, "status", c.ns, faultInjection), &v1alpha1.FaultInjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultInjection), err
}

// Delete takes name of the faultInjection and deletes it. Returns an error if one occurs.
func (c *FakeFaultInjections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(faultinjectionsResource, c.ns, name, opts), &v1alpha1.FaultInjection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFaultInjections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(faultinjectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FaultInjectionList{})
	return err
}

// Patch applies the patch and returns the patched faultInjection.
func (c *FakeFaultInjections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FaultInjection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(faultinjectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FaultInjection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FaultInjection), err
}
