/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FaultInjectionLister helps list FaultInjections.
// All objects returned here must be treated as read-only.
type FaultInjectionLister interface {
	// List lists all FaultInjections in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FaultInjection, err error)
	// FaultInjections returns an object that can list and get FaultInjections.
	FaultInjections(namespace string) FaultInjectionNamespaceLister
	FaultInjectionListerExpansion
}

// faultInjectionLister implements the FaultInjectionLister interface.
type faultInjectionLister struct {
	indexer cache.Indexer
}

// NewFaultInjectionLister returns a new FaultInjectionLister.
func NewFaultInjectionLister(indexer cache.Indexer) FaultInjectionLister {
	return &faultInjectionLister{indexer: indexer}
}

// List lists all FaultInjections in the indexer.
func (s *faultInjectionLister) List(selector labels.Selector) (ret []*v1alpha1.FaultInjection, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FaultInjection))
	})
	return ret, err
}

// FaultInjections returns an object that can list and get FaultInjections.
func (s *faultInjectionLister) FaultInjections(namespace string) FaultInjectionNamespaceLister {
	return faultInjectionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FaultInjectionNamespaceLister helps list and get FaultInjections.
// All objects returned here must be treated as read-only.
type FaultInjectionNamespaceLister interface {
	// List lists all FaultInjections in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FaultInjection, err error)
	// Get retrieves the FaultInjection from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FaultInjection, error)
	FaultInjectionNamespaceListerExpansion
}

// faultInjectionNamespaceLister implements the FaultInjectionNamespaceLister
// interface.
type faultInjectionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FaultInjections in the indexer for a given namespace.
func (s faultInjectionNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FaultInjection, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FaultInjection))
	})
	return ret, err
}

// Get retrieves the FaultInjection from the indexer for a given namespace and name.
func (s faultInjectionNamespaceLister) Get(name string) (*v1alpha1.FaultInjection, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("faultinjection"), name)
	}
	return obj.(*v1alpha1.FaultInjection), nil
}
