# permissions for end users to view managerstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managerstate-viewer-role
rules:
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - managerstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - managerstates/status
  verbs:
  - get
