
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kridge-kusionstack-role
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  - controllerrevisions
  - deployments
  - endpoints
  - persistentvolumeclaims
  - pods
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - ""
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - managerstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - managerstates/finalizers
  verbs:
  - update
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - managerstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - shardingconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - shardingconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kridge.kusionstack.io
  resources:
  - shardingconfigs/status
  verbs:
  - get
  - patch
  - update
