/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	ctrlmeshv1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	versioned "github.com/KusionStack/controller-mesh/pkg/client/clientset/versioned"
	internalinterfaces "github.com/KusionStack/controller-mesh/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/client/listers/ctrlmesh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ShardingConfigInformer provides access to a shared informer and lister for
// ShardingConfigs.
type ShardingConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ShardingConfigLister
}

type shardingConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewShardingConfigInformer constructs a new informer for ShardingConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewShardingConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredShardingConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredShardingConfigInformer constructs a new informer for ShardingConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredShardingConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CtrlmeshV1alpha1().ShardingConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CtrlmeshV1alpha1().ShardingConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&ctrlmeshv1alpha1.ShardingConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *shardingConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredShardingConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *shardingConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ctrlmeshv1alpha1.ShardingConfig{}, f.defaultInformer)
}

func (f *shardingConfigInformer) Lister() v1alpha1.ShardingConfigLister {
	return v1alpha1.NewShardingConfigLister(f.Informer().GetIndexer())
}
