// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/apis/kridge/proto/kridge.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProxyStatus struct {
	SelfInfo             *SelfInfo            `protobuf:"bytes,1,opt,name=selfInfo,proto3" json:"selfInfo,omitempty"`
	MetaState            *MetaState           `protobuf:"bytes,2,opt,name=metaState,proto3" json:"metaState,omitempty"`
	LeaderElectionState  *LeaderElectionState `protobuf:"bytes,3,opt,name=leaderElectionState,proto3" json:"leaderElectionState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProxyStatus) Reset()         { *m = ProxyStatus{} }
func (m *ProxyStatus) String() string { return proto.CompactTextString(m) }
func (*ProxyStatus) ProtoMessage()    {}
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{0}
}
func (m *ProxyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyStatus.Unmarshal(m, b)
}
func (m *ProxyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyStatus.Marshal(b, m, deterministic)
}
func (m *ProxyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyStatus.Merge(m, src)
}
func (m *ProxyStatus) XXX_Size() int {
	return xxx_messageInfo_ProxyStatus.Size(m)
}
func (m *ProxyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyStatus proto.InternalMessageInfo

func (m *ProxyStatus) GetSelfInfo() *SelfInfo {
	if m != nil {
		return m.SelfInfo
	}
	return nil
}

func (m *ProxyStatus) GetMetaState() *MetaState {
	if m != nil {
		return m.MetaState
	}
	return nil
}

func (m *ProxyStatus) GetLeaderElectionState() *LeaderElectionState {
	if m != nil {
		return m.LeaderElectionState
	}
	return nil
}

type SelfInfo struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfInfo) Reset()         { *m = SelfInfo{} }
func (m *SelfInfo) String() string { return proto.CompactTextString(m) }
func (*SelfInfo) ProtoMessage()    {}
func (*SelfInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{1}
}
func (m *SelfInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfInfo.Unmarshal(m, b)
}
func (m *SelfInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfInfo.Marshal(b, m, deterministic)
}
func (m *SelfInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfInfo.Merge(m, src)
}
func (m *SelfInfo) XXX_Size() int {
	return xxx_messageInfo_SelfInfo.Size(m)
}
func (m *SelfInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SelfInfo proto.InternalMessageInfo

func (m *SelfInfo) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SelfInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MetaState struct {
	ExpectedHash         string   `protobuf:"bytes,1,opt,name=expectedHash,proto3" json:"expectedHash,omitempty"`
	CurrentHash          string   `protobuf:"bytes,2,opt,name=currentHash,proto3" json:"currentHash,omitempty"`
	HashUnloadReason     string   `protobuf:"bytes,3,opt,name=hashUnloadReason,proto3" json:"hashUnloadReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaState) Reset()         { *m = MetaState{} }
func (m *MetaState) String() string { return proto.CompactTextString(m) }
func (*MetaState) ProtoMessage()    {}
func (*MetaState) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{2}
}
func (m *MetaState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaState.Unmarshal(m, b)
}
func (m *MetaState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaState.Marshal(b, m, deterministic)
}
func (m *MetaState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaState.Merge(m, src)
}
func (m *MetaState) XXX_Size() int {
	return xxx_messageInfo_MetaState.Size(m)
}
func (m *MetaState) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaState.DiscardUnknown(m)
}

var xxx_messageInfo_MetaState proto.InternalMessageInfo

func (m *MetaState) GetExpectedHash() string {
	if m != nil {
		return m.ExpectedHash
	}
	return ""
}

func (m *MetaState) GetCurrentHash() string {
	if m != nil {
		return m.CurrentHash
	}
	return ""
}

func (m *MetaState) GetHashUnloadReason() string {
	if m != nil {
		return m.HashUnloadReason
	}
	return ""
}

type LeaderElectionState struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IsLeader             bool     `protobuf:"varint,2,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderElectionState) Reset()         { *m = LeaderElectionState{} }
func (m *LeaderElectionState) String() string { return proto.CompactTextString(m) }
func (*LeaderElectionState) ProtoMessage()    {}
func (*LeaderElectionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{3}
}
func (m *LeaderElectionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderElectionState.Unmarshal(m, b)
}
func (m *LeaderElectionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderElectionState.Marshal(b, m, deterministic)
}
func (m *LeaderElectionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderElectionState.Merge(m, src)
}
func (m *LeaderElectionState) XXX_Size() int {
	return xxx_messageInfo_LeaderElectionState.Size(m)
}
func (m *LeaderElectionState) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderElectionState.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderElectionState proto.InternalMessageInfo

func (m *LeaderElectionState) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *LeaderElectionState) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

type ProxySpec struct {
	Meta                 *SpecMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Limits               []*Limit    `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty"`
	Endpoints            []*Endpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProxySpec) Reset()         { *m = ProxySpec{} }
func (m *ProxySpec) String() string { return proto.CompactTextString(m) }
func (*ProxySpec) ProtoMessage()    {}
func (*ProxySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{4}
}
func (m *ProxySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxySpec.Unmarshal(m, b)
}
func (m *ProxySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxySpec.Marshal(b, m, deterministic)
}
func (m *ProxySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxySpec.Merge(m, src)
}
func (m *ProxySpec) XXX_Size() int {
	return xxx_messageInfo_ProxySpec.Size(m)
}
func (m *ProxySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxySpec.DiscardUnknown(m)
}

var xxx_messageInfo_ProxySpec proto.InternalMessageInfo

func (m *ProxySpec) GetMeta() *SpecMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ProxySpec) GetLimits() []*Limit {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *ProxySpec) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type SpecMeta struct {
	ShardName            string   `protobuf:"bytes,1,opt,name=shardName,proto3" json:"shardName,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpecMeta) Reset()         { *m = SpecMeta{} }
func (m *SpecMeta) String() string { return proto.CompactTextString(m) }
func (*SpecMeta) ProtoMessage()    {}
func (*SpecMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{5}
}
func (m *SpecMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpecMeta.Unmarshal(m, b)
}
func (m *SpecMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpecMeta.Marshal(b, m, deterministic)
}
func (m *SpecMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpecMeta.Merge(m, src)
}
func (m *SpecMeta) XXX_Size() int {
	return xxx_messageInfo_SpecMeta.Size(m)
}
func (m *SpecMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_SpecMeta.DiscardUnknown(m)
}

var xxx_messageInfo_SpecMeta proto.InternalMessageInfo

func (m *SpecMeta) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *SpecMeta) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Limit struct {
	ObjectSelector       string              `protobuf:"bytes,1,opt,name=objectSelector,proto3" json:"objectSelector,omitempty"`
	Resources            []*APIGroupResource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Limit) Reset()         { *m = Limit{} }
func (m *Limit) String() string { return proto.CompactTextString(m) }
func (*Limit) ProtoMessage()    {}
func (*Limit) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{6}
}
func (m *Limit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Limit.Unmarshal(m, b)
}
func (m *Limit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Limit.Marshal(b, m, deterministic)
}
func (m *Limit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Limit.Merge(m, src)
}
func (m *Limit) XXX_Size() int {
	return xxx_messageInfo_Limit.Size(m)
}
func (m *Limit) XXX_DiscardUnknown() {
	xxx_messageInfo_Limit.DiscardUnknown(m)
}

var xxx_messageInfo_Limit proto.InternalMessageInfo

func (m *Limit) GetObjectSelector() string {
	if m != nil {
		return m.ObjectSelector
	}
	return ""
}

func (m *Limit) GetResources() []*APIGroupResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type APIGroupResource struct {
	ApiGroups            []string `protobuf:"bytes,1,rep,name=apiGroups,proto3" json:"apiGroups,omitempty"`
	Resources            []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIGroupResource) Reset()         { *m = APIGroupResource{} }
func (m *APIGroupResource) String() string { return proto.CompactTextString(m) }
func (*APIGroupResource) ProtoMessage()    {}
func (*APIGroupResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{7}
}
func (m *APIGroupResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIGroupResource.Unmarshal(m, b)
}
func (m *APIGroupResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIGroupResource.Marshal(b, m, deterministic)
}
func (m *APIGroupResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIGroupResource.Merge(m, src)
}
func (m *APIGroupResource) XXX_Size() int {
	return xxx_messageInfo_APIGroupResource.Size(m)
}
func (m *APIGroupResource) XXX_DiscardUnknown() {
	xxx_messageInfo_APIGroupResource.DiscardUnknown(m)
}

var xxx_messageInfo_APIGroupResource proto.InternalMessageInfo

func (m *APIGroupResource) GetApiGroups() []string {
	if m != nil {
		return m.ApiGroups
	}
	return nil
}

func (m *APIGroupResource) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Endpoint struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	ShardName            string   `protobuf:"bytes,3,opt,name=shardName,proto3" json:"shardName,omitempty"`
	Limits               []*Limit `protobuf:"bytes,4,rep,name=limits,proto3" json:"limits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_220bdee20b2fa748, []int{8}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Endpoint) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Endpoint) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *Endpoint) GetLimits() []*Limit {
	if m != nil {
		return m.Limits
	}
	return nil
}

func init() {
	proto.RegisterType((*ProxyStatus)(nil), "proto.ProxyStatus")
	proto.RegisterType((*SelfInfo)(nil), "proto.SelfInfo")
	proto.RegisterType((*MetaState)(nil), "proto.MetaState")
	proto.RegisterType((*LeaderElectionState)(nil), "proto.LeaderElectionState")
	proto.RegisterType((*ProxySpec)(nil), "proto.ProxySpec")
	proto.RegisterType((*SpecMeta)(nil), "proto.SpecMeta")
	proto.RegisterType((*Limit)(nil), "proto.Limit")
	proto.RegisterType((*APIGroupResource)(nil), "proto.APIGroupResource")
	proto.RegisterType((*Endpoint)(nil), "proto.Endpoint")
}

func init() {
	proto.RegisterFile("pkg/apis/kridge/proto/kridge.proto", fileDescriptor_220bdee20b2fa748)
}

var fileDescriptor_220bdee20b2fa748 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x6d, 0x37, 0x92, 0xd7, 0xa9, 0x54, 0xde, 0x81, 0xa8, 0xe2, 0x50, 0x05, 0x84, 0x2a,
	0x10, 0x2d, 0x2a, 0x82, 0x13, 0x17, 0x40, 0x13, 0x9b, 0xb4, 0x4e, 0x93, 0x2b, 0x2e, 0xdc, 0xbc,
	0xe4, 0xb5, 0x31, 0x4b, 0x63, 0xcb, 0x76, 0xa5, 0xed, 0xc0, 0x91, 0xff, 0xc4, 0xcf, 0x43, 0x76,
	0x9c, 0xa4, 0xed, 0xc6, 0x29, 0x79, 0xdf, 0xfb, 0x3e, 0xfb, 0xbd, 0xef, 0x4b, 0x0b, 0x89, 0xbc,
	0x5d, 0xcf, 0x98, 0xe4, 0x7a, 0x76, 0xab, 0x78, 0xb6, 0xc6, 0x99, 0x54, 0xc2, 0x08, 0x5f, 0x4c,
	0x5d, 0x41, 0x8e, 0xdc, 0x23, 0xf9, 0x1b, 0x40, 0xff, 0x5a, 0x89, 0xbb, 0xfb, 0xa5, 0x61, 0x66,
	0xab, 0xc9, 0x5b, 0x08, 0x35, 0x16, 0xab, 0x8b, 0x72, 0x25, 0xe2, 0x60, 0x1c, 0x4c, 0xfa, 0xf3,
	0x67, 0x95, 0x60, 0xba, 0xf4, 0x30, 0x6d, 0x08, 0x64, 0x0a, 0xd1, 0x06, 0x0d, 0xb3, 0x52, 0x8c,
	0x3b, 0x8e, 0x3d, 0xf4, 0xec, 0x45, 0x8d, 0xd3, 0x96, 0x42, 0x2e, 0xe1, 0xb4, 0x40, 0x96, 0xa1,
	0x3a, 0x2b, 0x30, 0x35, 0x5c, 0x94, 0x95, 0xb2, 0xeb, 0x94, 0x23, 0xaf, 0xbc, 0x7c, 0xc8, 0xa0,
	0x8f, 0xc9, 0x92, 0xcf, 0x10, 0xd6, 0x33, 0x91, 0x17, 0x10, 0x95, 0x6c, 0x83, 0x5a, 0xb2, 0x14,
	0xdd, 0xdc, 0x11, 0x6d, 0x01, 0x42, 0xa0, 0x67, 0x0b, 0x37, 0x62, 0x44, 0xdd, 0x7b, 0xf2, 0x1b,
	0xa2, 0x66, 0x46, 0x92, 0xc0, 0x09, 0xde, 0x49, 0x4c, 0x0d, 0x66, 0xe7, 0x4c, 0xe7, 0xfe, 0x84,
	0x3d, 0x8c, 0x8c, 0xa1, 0x9f, 0x6e, 0x95, 0xc2, 0xd2, 0x38, 0x4a, 0x75, 0xd6, 0x2e, 0x44, 0xde,
	0xc0, 0x30, 0x67, 0x3a, 0xff, 0x51, 0x16, 0x82, 0x65, 0x14, 0x99, 0x16, 0xa5, 0xdb, 0x2d, 0xa2,
	0x0f, 0xf0, 0x64, 0x01, 0xa7, 0x8f, 0x2c, 0x4a, 0x46, 0x10, 0xf2, 0x0c, 0x4b, 0xc3, 0xcd, 0xbd,
	0x1f, 0xa2, 0xa9, 0x5d, 0x4f, 0x57, 0x22, 0x77, 0x7b, 0x48, 0x9b, 0x3a, 0xf9, 0x13, 0x40, 0x54,
	0xc5, 0x28, 0x31, 0x25, 0x2f, 0xa1, 0x67, 0x4d, 0x3f, 0x0c, 0x50, 0x62, 0x6a, 0x57, 0xa6, 0xae,
	0x49, 0x5e, 0xc1, 0x71, 0xc1, 0x37, 0xdc, 0xe8, 0xb8, 0x33, 0xee, 0x4e, 0xfa, 0xf3, 0x93, 0xda,
	0x7f, 0x0b, 0x52, 0xdf, 0x23, 0xef, 0x20, 0xc2, 0x32, 0x93, 0x82, 0x97, 0x46, 0xc7, 0x5d, 0x47,
	0xac, 0xcf, 0x3b, 0xf3, 0x38, 0x6d, 0x19, 0x2e, 0x13, 0x7f, 0x8d, 0xcd, 0x44, 0xe7, 0x4c, 0x65,
	0x57, 0xd6, 0x7a, 0x9f, 0x49, 0x03, 0xd8, 0x4c, 0xf2, 0xd6, 0x47, 0xf7, 0x9e, 0xac, 0xe0, 0xc8,
	0xdd, 0x4e, 0x5e, 0xc3, 0x40, 0xdc, 0xfc, 0xc2, 0xd4, 0x2c, 0xd1, 0xda, 0x23, 0x94, 0xd7, 0x1f,
	0xa0, 0xe4, 0x23, 0x44, 0x0a, 0xb5, 0xd8, 0xaa, 0x14, 0xeb, 0x35, 0x9e, 0xfb, 0xe9, 0xbe, 0x5c,
	0x5f, 0x7c, 0x57, 0x62, 0x2b, 0xa9, 0xef, 0xd3, 0x96, 0x99, 0x5c, 0xc1, 0xf0, 0xb0, 0x6d, 0xa7,
	0x65, 0x92, 0x3b, 0x4c, 0xc7, 0xc1, 0xb8, 0x6b, 0xa7, 0x6d, 0x00, 0xdb, 0xdd, 0xbf, 0x28, 0xda,
	0x3d, 0x4f, 0x41, 0x58, 0x9b, 0xd1, 0x7c, 0x6b, 0x41, 0xfb, 0xad, 0x91, 0x01, 0x74, 0xb8, 0xf4,
	0x9b, 0x76, 0xb8, 0xdc, 0x77, 0xa6, 0x7b, 0xe8, 0x4c, 0x1b, 0x4c, 0xef, 0xff, 0xc1, 0xcc, 0xcf,
	0x61, 0xf0, 0x4d, 0x94, 0x46, 0x89, 0xa2, 0x40, 0xb5, 0x40, 0x9d, 0x93, 0x4f, 0x10, 0x52, 0x5c,
	0x73, 0x6d, 0x50, 0x11, 0xe2, 0x35, 0x3b, 0x3f, 0xed, 0xd1, 0x70, 0x0f, 0x93, 0x98, 0x26, 0x4f,
	0x26, 0xc1, 0xfb, 0xe0, 0xeb, 0xd3, 0x9f, 0xd5, 0x7f, 0xc1, 0xcd, 0xb1, 0x7b, 0x7c, 0xf8, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x2a, 0x31, 0x1f, 0x45, 0x3f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerMeshClient is the client API for ControllerMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerMeshClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (ControllerMesh_RegisterClient, error)
}

type controllerMeshClient struct {
	cc *grpc.ClientConn
}

func NewControllerMeshClient(cc *grpc.ClientConn) ControllerMeshClient {
	return &controllerMeshClient{cc}
}

func (c *controllerMeshClient) Register(ctx context.Context, opts ...grpc.CallOption) (ControllerMesh_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ControllerMesh_serviceDesc.Streams[0], "/proto.ControllerMesh/Register", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerMeshRegisterClient{stream}
	return x, nil
}

type ControllerMesh_RegisterClient interface {
	Send(*ProxyStatus) error
	Recv() (*ProxySpec, error)
	grpc.ClientStream
}

type controllerMeshRegisterClient struct {
	grpc.ClientStream
}

func (x *controllerMeshRegisterClient) Send(m *ProxyStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerMeshRegisterClient) Recv() (*ProxySpec, error) {
	m := new(ProxySpec)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerMeshServer is the server API for ControllerMesh service.
type ControllerMeshServer interface {
	Register(ControllerMesh_RegisterServer) error
}

// UnimplementedControllerMeshServer can be embedded to have forward compatible implementations.
type UnimplementedControllerMeshServer struct {
}

func (*UnimplementedControllerMeshServer) Register(srv ControllerMesh_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterControllerMeshServer(s *grpc.Server, srv ControllerMeshServer) {
	s.RegisterService(&_ControllerMesh_serviceDesc, srv)
}

func _ControllerMesh_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerMeshServer).Register(&controllerMeshRegisterServer{stream})
}

type ControllerMesh_RegisterServer interface {
	Send(*ProxySpec) error
	Recv() (*ProxyStatus, error)
	grpc.ServerStream
}

type controllerMeshRegisterServer struct {
	grpc.ServerStream
}

func (x *controllerMeshRegisterServer) Send(m *ProxySpec) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerMeshRegisterServer) Recv() (*ProxyStatus, error) {
	m := new(ProxyStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ControllerMesh_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ControllerMesh",
	HandlerType: (*ControllerMeshServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _ControllerMesh_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/apis/kridge/proto/kridge.proto",
}
