---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-operator-v0
  namespace: system
  labels:
    controller-version: v0
    control-plane: controller-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 2
  template:
    metadata:
      labels:
        #ctrlmesh.kusionstack.io/enable-proxy: "true"
        #ctrlmesh.kusionstack.io/watching: "true"
        control-plane: controller-manager
        controller-version: v0                       # version label: v0
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect=true
        - --leader-election-name=sample-operator-leader
        - --controller-version=v0
        image: controller:latest
        name: manager
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
