/*
Copyright 2023 The KusionStack Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/KusionStack/controller-mesh/pkg/apis/ctrlmesh/v1alpha1"
	scheme "github.com/KusionStack/controller-mesh/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CircuitBreakersGetter has a method to return a CircuitBreakerInterface.
// A group's client should implement this interface.
type CircuitBreakersGetter interface {
	CircuitBreakers(namespace string) CircuitBreakerInterface
}

// CircuitBreakerInterface has methods to work with CircuitBreaker resources.
type CircuitBreakerInterface interface {
	Create(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.CreateOptions) (*v1alpha1.CircuitBreaker, error)
	Update(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (*v1alpha1.CircuitBreaker, error)
	UpdateStatus(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (*v1alpha1.CircuitBreaker, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CircuitBreaker, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CircuitBreakerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CircuitBreaker, err error)
	CircuitBreakerExpansion
}

// circuitBreakers implements CircuitBreakerInterface
type circuitBreakers struct {
	client rest.Interface
	ns     string
}

// newCircuitBreakers returns a CircuitBreakers
func newCircuitBreakers(c *CtrlmeshV1alpha1Client, namespace string) *circuitBreakers {
	return &circuitBreakers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the circuitBreaker, and returns the corresponding circuitBreaker object, and an error if there is any.
func (c *circuitBreakers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CircuitBreaker, err error) {
	result = &v1alpha1.CircuitBreaker{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("circuitbreakers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CircuitBreakers that match those selectors.
func (c *circuitBreakers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CircuitBreakerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CircuitBreakerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("circuitbreakers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested circuitBreakers.
func (c *circuitBreakers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("circuitbreakers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a circuitBreaker and creates it.  Returns the server's representation of the circuitBreaker, and an error, if there is any.
func (c *circuitBreakers) Create(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.CreateOptions) (result *v1alpha1.CircuitBreaker, err error) {
	result = &v1alpha1.CircuitBreaker{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("circuitbreakers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(circuitBreaker).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a circuitBreaker and updates it. Returns the server's representation of the circuitBreaker, and an error, if there is any.
func (c *circuitBreakers) Update(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (result *v1alpha1.CircuitBreaker, err error) {
	result = &v1alpha1.CircuitBreaker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("circuitbreakers").
		Name(circuitBreaker.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(circuitBreaker).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *circuitBreakers) UpdateStatus(ctx context.Context, circuitBreaker *v1alpha1.CircuitBreaker, opts v1.UpdateOptions) (result *v1alpha1.CircuitBreaker, err error) {
	result = &v1alpha1.CircuitBreaker{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("circuitbreakers").
		Name(circuitBreaker.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(circuitBreaker).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the circuitBreaker and deletes it. Returns an error if one occurs.
func (c *circuitBreakers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("circuitbreakers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *circuitBreakers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("circuitbreakers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched circuitBreaker.
func (c *circuitBreakers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CircuitBreaker, err error) {
	result = &v1alpha1.CircuitBreaker{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("circuitbreakers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
