// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: pkg/apis/ctrlmesh/proto/ctrlmesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfInfo            *SelfInfo            `protobuf:"bytes,1,opt,name=selfInfo,proto3" json:"selfInfo,omitempty"`
	MetaState           *MetaState           `protobuf:"bytes,2,opt,name=metaState,proto3" json:"metaState,omitempty"`
	LeaderElectionState *LeaderElectionState `protobuf:"bytes,3,opt,name=leaderElectionState,proto3" json:"leaderElectionState,omitempty"`
}

func (x *ProxyStatus) Reset() {
	*x = ProxyStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyStatus) ProtoMessage() {}

func (x *ProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyStatus.ProtoReflect.Descriptor instead.
func (*ProxyStatus) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyStatus) GetSelfInfo() *SelfInfo {
	if x != nil {
		return x.SelfInfo
	}
	return nil
}

func (x *ProxyStatus) GetMetaState() *MetaState {
	if x != nil {
		return x.MetaState
	}
	return nil
}

func (x *ProxyStatus) GetLeaderElectionState() *LeaderElectionState {
	if x != nil {
		return x.LeaderElectionState
	}
	return nil
}

type SelfInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SelfInfo) Reset() {
	*x = SelfInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelfInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfInfo) ProtoMessage() {}

func (x *SelfInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfInfo.ProtoReflect.Descriptor instead.
func (*SelfInfo) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{1}
}

func (x *SelfInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SelfInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MetaState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpectedHash     string `protobuf:"bytes,1,opt,name=expectedHash,proto3" json:"expectedHash,omitempty"`
	CurrentHash      string `protobuf:"bytes,2,opt,name=currentHash,proto3" json:"currentHash,omitempty"`
	HashUnloadReason string `protobuf:"bytes,3,opt,name=hashUnloadReason,proto3" json:"hashUnloadReason,omitempty"`
}

func (x *MetaState) Reset() {
	*x = MetaState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaState) ProtoMessage() {}

func (x *MetaState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaState.ProtoReflect.Descriptor instead.
func (*MetaState) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{2}
}

func (x *MetaState) GetExpectedHash() string {
	if x != nil {
		return x.ExpectedHash
	}
	return ""
}

func (x *MetaState) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

func (x *MetaState) GetHashUnloadReason() string {
	if x != nil {
		return x.HashUnloadReason
	}
	return ""
}

type LeaderElectionState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	IsLeader bool   `protobuf:"varint,2,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
}

func (x *LeaderElectionState) Reset() {
	*x = LeaderElectionState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderElectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderElectionState) ProtoMessage() {}

func (x *LeaderElectionState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderElectionState.ProtoReflect.Descriptor instead.
func (*LeaderElectionState) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderElectionState) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *LeaderElectionState) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type ProxySpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta      *SpecMeta   `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Limits    []*Limit    `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty"`
	Endpoints []*Endpoint `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *ProxySpec) Reset() {
	*x = ProxySpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxySpec) ProtoMessage() {}

func (x *ProxySpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxySpec.ProtoReflect.Descriptor instead.
func (*ProxySpec) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{4}
}

func (x *ProxySpec) GetMeta() *SpecMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProxySpec) GetLimits() []*Limit {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ProxySpec) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type SpecMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShardName string `protobuf:"bytes,1,opt,name=shardName,proto3" json:"shardName,omitempty"`
	Hash      string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *SpecMeta) Reset() {
	*x = SpecMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpecMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecMeta) ProtoMessage() {}

func (x *SpecMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecMeta.ProtoReflect.Descriptor instead.
func (*SpecMeta) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{5}
}

func (x *SpecMeta) GetShardName() string {
	if x != nil {
		return x.ShardName
	}
	return ""
}

func (x *SpecMeta) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type Limit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectSelector string              `protobuf:"bytes,1,opt,name=objectSelector,proto3" json:"objectSelector,omitempty"`
	Resources      []*APIGroupResource `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *Limit) Reset() {
	*x = Limit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limit) ProtoMessage() {}

func (x *Limit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limit.ProtoReflect.Descriptor instead.
func (*Limit) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{6}
}

func (x *Limit) GetObjectSelector() string {
	if x != nil {
		return x.ObjectSelector
	}
	return ""
}

func (x *Limit) GetResources() []*APIGroupResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type APIGroupResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiGroups []string `protobuf:"bytes,1,rep,name=apiGroups,proto3" json:"apiGroups,omitempty"`
	Resources []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *APIGroupResource) Reset() {
	*x = APIGroupResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIGroupResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIGroupResource) ProtoMessage() {}

func (x *APIGroupResource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIGroupResource.ProtoReflect.Descriptor instead.
func (*APIGroupResource) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{7}
}

func (x *APIGroupResource) GetApiGroups() []string {
	if x != nil {
		return x.ApiGroups
	}
	return nil
}

func (x *APIGroupResource) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ip        string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	ShardName string   `protobuf:"bytes,3,opt,name=shardName,proto3" json:"shardName,omitempty"`
	Limits    []*Limit `protobuf:"bytes,4,rep,name=limits,proto3" json:"limits,omitempty"`
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Endpoint) GetShardName() string {
	if x != nil {
		return x.ShardName
	}
	return ""
}

func (x *Endpoint) GetLimits() []*Limit {
	if x != nil {
		return x.Limits
	}
	return nil
}

var File_pkg_apis_ctrlmesh_proto_ctrlmesh_proto protoreflect.FileDescriptor

var file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x6d,
	0x65, 0x73, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x65,
	0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb8, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x2b, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x66, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x09,
	0x6d, 0x65, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x13,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x13, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3c, 0x0a, 0x08, 0x53, 0x65,
	0x6c, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x10, 0x68,
	0x61, 0x73, 0x68, 0x55, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68, 0x61, 0x73, 0x68, 0x55, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x23, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12,
	0x2d, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x3c,
	0x0a, 0x08, 0x53, 0x70, 0x65, 0x63, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x66, 0x0a, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x35, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x50, 0x49, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x41, 0x50, 0x49, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x69,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x32, 0x48, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x68, 0x12, 0x36, 0x0a, 0x08, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x70, 0x65, 0x63, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x63, 0x74, 0x72, 0x6c, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescOnce sync.Once
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescData = file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDesc
)

func file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescGZIP() []byte {
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescOnce.Do(func() {
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescData)
	})
	return file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDescData
}

var file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_goTypes = []interface{}{
	(*ProxyStatus)(nil),         // 0: proto.ProxyStatus
	(*SelfInfo)(nil),            // 1: proto.SelfInfo
	(*MetaState)(nil),           // 2: proto.MetaState
	(*LeaderElectionState)(nil), // 3: proto.LeaderElectionState
	(*ProxySpec)(nil),           // 4: proto.ProxySpec
	(*SpecMeta)(nil),            // 5: proto.SpecMeta
	(*Limit)(nil),               // 6: proto.Limit
	(*APIGroupResource)(nil),    // 7: proto.APIGroupResource
	(*Endpoint)(nil),            // 8: proto.Endpoint
}
var file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_depIdxs = []int32{
	1, // 0: proto.ProxyStatus.selfInfo:type_name -> proto.SelfInfo
	2, // 1: proto.ProxyStatus.metaState:type_name -> proto.MetaState
	3, // 2: proto.ProxyStatus.leaderElectionState:type_name -> proto.LeaderElectionState
	5, // 3: proto.ProxySpec.meta:type_name -> proto.SpecMeta
	6, // 4: proto.ProxySpec.limits:type_name -> proto.Limit
	8, // 5: proto.ProxySpec.endpoints:type_name -> proto.Endpoint
	7, // 6: proto.Limit.resources:type_name -> proto.APIGroupResource
	6, // 7: proto.Endpoint.limits:type_name -> proto.Limit
	0, // 8: proto.ControllerMesh.Register:input_type -> proto.ProxyStatus
	4, // 9: proto.ControllerMesh.Register:output_type -> proto.ProxySpec
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_init() }
func file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_init() {
	if File_pkg_apis_ctrlmesh_proto_ctrlmesh_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxyStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelfInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderElectionState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProxySpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpecMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Limit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIGroupResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_goTypes,
		DependencyIndexes: file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_depIdxs,
		MessageInfos:      file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_msgTypes,
	}.Build()
	File_pkg_apis_ctrlmesh_proto_ctrlmesh_proto = out.File
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_rawDesc = nil
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_goTypes = nil
	file_pkg_apis_ctrlmesh_proto_ctrlmesh_proto_depIdxs = nil
}
