// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package proto

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using ProxyStatus within kubernetes types, where deepcopy-gen is used.
func (in *ProxyStatus) DeepCopyInto(out *ProxyStatus) {
	p := proto.Clone(in).(*ProxyStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyStatus. Required by controller-gen.
func (in *ProxyStatus) DeepCopy() *ProxyStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ProxyStatus. Required by controller-gen.
func (in *ProxyStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SelfInfo within kubernetes types, where deepcopy-gen is used.
func (in *SelfInfo) DeepCopyInto(out *SelfInfo) {
	p := proto.Clone(in).(*SelfInfo)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfInfo. Required by controller-gen.
func (in *SelfInfo) DeepCopy() *SelfInfo {
	if in == nil {
		return nil
	}
	out := new(SelfInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SelfInfo. Required by controller-gen.
func (in *SelfInfo) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MetaState within kubernetes types, where deepcopy-gen is used.
func (in *MetaState) DeepCopyInto(out *MetaState) {
	p := proto.Clone(in).(*MetaState)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaState. Required by controller-gen.
func (in *MetaState) DeepCopy() *MetaState {
	if in == nil {
		return nil
	}
	out := new(MetaState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MetaState. Required by controller-gen.
func (in *MetaState) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LeaderElectionState within kubernetes types, where deepcopy-gen is used.
func (in *LeaderElectionState) DeepCopyInto(out *LeaderElectionState) {
	p := proto.Clone(in).(*LeaderElectionState)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionState. Required by controller-gen.
func (in *LeaderElectionState) DeepCopy() *LeaderElectionState {
	if in == nil {
		return nil
	}
	out := new(LeaderElectionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LeaderElectionState. Required by controller-gen.
func (in *LeaderElectionState) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ProxySpec within kubernetes types, where deepcopy-gen is used.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	p := proto.Clone(in).(*ProxySpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec. Required by controller-gen.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec. Required by controller-gen.
func (in *ProxySpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using SpecMeta within kubernetes types, where deepcopy-gen is used.
func (in *SpecMeta) DeepCopyInto(out *SpecMeta) {
	p := proto.Clone(in).(*SpecMeta)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecMeta. Required by controller-gen.
func (in *SpecMeta) DeepCopy() *SpecMeta {
	if in == nil {
		return nil
	}
	out := new(SpecMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new SpecMeta. Required by controller-gen.
func (in *SpecMeta) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Limit within kubernetes types, where deepcopy-gen is used.
func (in *Limit) DeepCopyInto(out *Limit) {
	p := proto.Clone(in).(*Limit)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limit. Required by controller-gen.
func (in *Limit) DeepCopy() *Limit {
	if in == nil {
		return nil
	}
	out := new(Limit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Limit. Required by controller-gen.
func (in *Limit) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using APIGroupResource within kubernetes types, where deepcopy-gen is used.
func (in *APIGroupResource) DeepCopyInto(out *APIGroupResource) {
	p := proto.Clone(in).(*APIGroupResource)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIGroupResource. Required by controller-gen.
func (in *APIGroupResource) DeepCopy() *APIGroupResource {
	if in == nil {
		return nil
	}
	out := new(APIGroupResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new APIGroupResource. Required by controller-gen.
func (in *APIGroupResource) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Endpoint within kubernetes types, where deepcopy-gen is used.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	p := proto.Clone(in).(*Endpoint)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint. Required by controller-gen.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint. Required by controller-gen.
func (in *Endpoint) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
