// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package proto

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using CircuitBreaker within kubernetes types, where deepcopy-gen is used.
func (in *CircuitBreaker) DeepCopyInto(out *CircuitBreaker) {
	p := proto.Clone(in).(*CircuitBreaker)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreaker. Required by controller-gen.
func (in *CircuitBreaker) DeepCopy() *CircuitBreaker {
	if in == nil {
		return nil
	}
	out := new(CircuitBreaker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreaker. Required by controller-gen.
func (in *CircuitBreaker) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ConfigResp within kubernetes types, where deepcopy-gen is used.
func (in *ConfigResp) DeepCopyInto(out *ConfigResp) {
	p := proto.Clone(in).(*ConfigResp)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigResp. Required by controller-gen.
func (in *ConfigResp) DeepCopy() *ConfigResp {
	if in == nil {
		return nil
	}
	out := new(ConfigResp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ConfigResp. Required by controller-gen.
func (in *ConfigResp) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LimitingSnapshot within kubernetes types, where deepcopy-gen is used.
func (in *LimitingSnapshot) DeepCopyInto(out *LimitingSnapshot) {
	p := proto.Clone(in).(*LimitingSnapshot)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitingSnapshot. Required by controller-gen.
func (in *LimitingSnapshot) DeepCopy() *LimitingSnapshot {
	if in == nil {
		return nil
	}
	out := new(LimitingSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LimitingSnapshot. Required by controller-gen.
func (in *LimitingSnapshot) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using TrafficInterceptRule within kubernetes types, where deepcopy-gen is used.
func (in *TrafficInterceptRule) DeepCopyInto(out *TrafficInterceptRule) {
	p := proto.Clone(in).(*TrafficInterceptRule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficInterceptRule. Required by controller-gen.
func (in *TrafficInterceptRule) DeepCopy() *TrafficInterceptRule {
	if in == nil {
		return nil
	}
	out := new(TrafficInterceptRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new TrafficInterceptRule. Required by controller-gen.
func (in *TrafficInterceptRule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RateLimiting within kubernetes types, where deepcopy-gen is used.
func (in *RateLimiting) DeepCopyInto(out *RateLimiting) {
	p := proto.Clone(in).(*RateLimiting)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting. Required by controller-gen.
func (in *RateLimiting) DeepCopy() *RateLimiting {
	if in == nil {
		return nil
	}
	out := new(RateLimiting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting. Required by controller-gen.
func (in *RateLimiting) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RateLimiting_RecoverPolicy within kubernetes types, where deepcopy-gen is used.
func (in *RateLimiting_RecoverPolicy) DeepCopyInto(out *RateLimiting_RecoverPolicy) {
	p := proto.Clone(in).(*RateLimiting_RecoverPolicy)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting_RecoverPolicy. Required by controller-gen.
func (in *RateLimiting_RecoverPolicy) DeepCopy() *RateLimiting_RecoverPolicy {
	if in == nil {
		return nil
	}
	out := new(RateLimiting_RecoverPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiting_RecoverPolicy. Required by controller-gen.
func (in *RateLimiting_RecoverPolicy) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ResourceRule within kubernetes types, where deepcopy-gen is used.
func (in *ResourceRule) DeepCopyInto(out *ResourceRule) {
	p := proto.Clone(in).(*ResourceRule)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRule. Required by controller-gen.
func (in *ResourceRule) DeepCopy() *ResourceRule {
	if in == nil {
		return nil
	}
	out := new(ResourceRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRule. Required by controller-gen.
func (in *ResourceRule) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using RestRules within kubernetes types, where deepcopy-gen is used.
func (in *RestRules) DeepCopyInto(out *RestRules) {
	p := proto.Clone(in).(*RestRules)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestRules. Required by controller-gen.
func (in *RestRules) DeepCopy() *RestRules {
	if in == nil {
		return nil
	}
	out := new(RestRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new RestRules. Required by controller-gen.
func (in *RestRules) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Bucket within kubernetes types, where deepcopy-gen is used.
func (in *Bucket) DeepCopyInto(out *Bucket) {
	p := proto.Clone(in).(*Bucket)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bucket. Required by controller-gen.
func (in *Bucket) DeepCopy() *Bucket {
	if in == nil {
		return nil
	}
	out := new(Bucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Bucket. Required by controller-gen.
func (in *Bucket) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
