name: CI

on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.18'
  GOLANGCI_VERSION: 'v1.42'

jobs:

  ci-build-test:
    name: ci-build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.15.x'
      - name: Build and Test
        run: |
          make build test
      - name: Check diff
        run: |
          git status
          [[ -z $(git status -s) ]] || (git status; printf "Existing modified/untracked files.\nPlease run \"make generate manifests\" and push again.\n"; exit 1)